apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openquant.fullname" . }}-config
  labels:
    {{- include "openquant.labels" . | nindent 4 }}
data:
  ENVIRONMENT: {{ .Values.global.environment | quote }}
  LOG_LEVEL: {{ .Values.backend.env.LOG_LEVEL | quote }}
  ALLOWED_ORIGINS: {{ .Values.backend.env.ALLOWED_ORIGINS | quote }}
