"""Domain models for Quantitative Strategy definition, parameters, state, and signals."""

from datetime import datetime, timezone
from enum import StrEnum
from decimal import Decimal
from typing import Any
from pydantic import BaseModel, Field
from openquant.domain.models.promotion import StrategyPromotionStage


class StrategyState(StrEnum):
    """Execution lifecycle state of a strategy."""
    DRAFT = "DRAFT"
    INITIALIZED = "INITIALIZED"
    RUNNING = "RUNNING"
    PAUSED = "PAUSED"
    STOPPED = "STOPPED"
    ERROR = "ERROR"


class ParameterType(StrEnum):
    """Data types for strategy configurable parameters."""
    INT = "INT"
    FLOAT = "FLOAT"
    STRING = "STRING"
    BOOLEAN = "BOOLEAN"


class StrategyParameter(BaseModel):
    """Metadata and bounds for a strategy input parameter."""
    name: str
    param_type: ParameterType = ParameterType.FLOAT
    default_value: Any
    current_value: Any
    min_value: float | None = None
    max_value: float | None = None
    description: str = ""


class StrategySignal(BaseModel):
    """Trading signal generated by strategy logic during runtime execution."""
    symbol: str
    signal_type: str = Field(..., description="BUY | SELL | HOLD | CLOSE")
    confidence: float = Field(default=1.0, ge=0.0, le=1.0)
    suggested_quantity: Decimal | None = None
    suggested_price: Decimal | None = None
    metadata: dict[str, Any] = Field(default_factory=dict)
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class Strategy(BaseModel):
    """Domain Entity representing a quantitative trading strategy."""
    strategy_id: str
    name: str
    description: str = ""
    author_id: str = "system"
    source_code: str
    parameters: list[StrategyParameter] = Field(default_factory=list)
    promotion_stage: StrategyPromotionStage = StrategyPromotionStage.DRAFT
    state: StrategyState = StrategyState.INITIALIZED
    symbols: list[str] = Field(default_factory=lambda: ["AAPL"])
    timeframes: list[str] = Field(default_factory=lambda: ["1m"])
    account_id: str = "acc_main"
    broker_id: str = "paper_broker"
    total_trades: int = 0
    winning_trades: int = 0
    total_pnl: Decimal = Decimal("0")
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    updated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    @property
    def is_active(self) -> bool:
        """Check if strategy is actively receiving ticks and generating signals."""
        return self.state == StrategyState.RUNNING

    def get_parameter_dict(self) -> dict[str, Any]:
        """Resolve current parameters as key-value dictionary."""
        return {p.name: p.current_value for p in self.parameters}
